-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.4.32-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             12.1.0.6537
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping structure for table student_practical.lt_course
CREATE TABLE IF NOT EXISTS `lt_course` (
  `id_course` int(3) NOT NULL AUTO_INCREMENT,
  `name_course` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`id_course`)
) ENGINE=InnoDB AUTO_INCREMENT=87 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table student_practical.lt_course: ~86 rows (approximately)
INSERT IGNORE INTO `lt_course` (`id_course`, `name_course`) VALUES
	(1, 'AKADEMIK KECEMERLANGAN'),
	(2, 'ALAM SEKITAR'),
	(3, 'ARKEOLOGI'),
	(4, 'ASAS SAINS KOMPUTER'),
	(5, 'ASTRONOMI'),
	(6, 'BAHASA ARAB'),
	(7, 'BAHASA INGGERIS'),
	(8, 'BIOKIMIA'),
	(9, 'BIOTEKNOLOGI'),
	(10, 'EKONOMI'),
	(11, 'FIZIK'),
	(12, 'GEOLOGI'),
	(13, 'GEOGRAFI'),
	(14, 'HOSPITALITI'),
	(15, 'KEJURUTERAAN ELEKTRIK'),
	(16, 'KEJURUTERAAN KIMIA'),
	(17, 'KEJURUTERAAN MEKANIKAL'),
	(18, 'KEJURUTERAAN PERISIAN'),
	(19, 'KESELAMATAN AWAM'),
	(20, 'KESIHATAN AWAM'),
	(21, 'KESIHATAN PERSEKITARAN'),
	(22, 'KEUSAHAWANAN'),
	(23, 'KEWANGAN'),
	(24, 'KEWARTAWANAN'),
	(25, 'KOMUNIKASI ANTARABANGSA'),
	(26, 'KOMUNIKASI KORPORAT'),
	(27, 'KOMUNIKASI MASA KINI'),
	(28, 'PENDIDIKAN'),
	(29, 'PENDIDIKAN BAHASA INGGERIS'),
	(30, 'PENDIDIKAN ISLAM'),
	(31, 'PENDIDIKAN JASMANI'),
	(32, 'PENDIDIKAN KANAK-KANAK'),
	(33, 'PENDIDIKAN KHAS'),
	(34, 'PENDIDIKAN MATEMATIK'),
	(35, 'PENDIDIKAN PENDIDIKAN KHAS'),
	(36, 'PENDIDIKAN PENDIDIKAN UNTUK PENDIDIK'),
	(37, 'PENDIDIKAN PERUNDANGAN'),
	(38, 'PENDIDIKAN SENI VISUAL'),
	(39, 'PENDIDIKAN SIVIK'),
	(40, 'PENDIDIKAN TEKNOLOGI'),
	(41, 'PENDIDIKAN TINGGI'),
	(42, 'PENDIDIKAN UNTUK PENDIDIK'),
	(43, 'PENDIDIKAN VOKASIONAL'),
	(44, 'PENDIDIKAN SAINS'),
	(45, 'PEMBANGUNAN KOMUNITI'),
	(46, 'PEMBANGUNAN SOSIAL'),
	(47, 'PEMASARAN'),
	(48, 'PERUNDANGAN'),
	(49, 'PENGURUSAN'),
	(50, 'PENGURUSAN BUKU'),
	(51, 'PENGURUSAN EKONOMI'),
	(52, 'PENGURUSAN HOTEL'),
	(53, 'PENGURUSAN KANAK-KANAK'),
	(54, 'PENGURUSAN KESIHATAN'),
	(55, 'PENGURUSAN KUALITI'),
	(56, 'PENGURUSAN PERNIAGAAN'),
	(57, 'PENGURUSAN PELANCONGAN'),
	(58, 'PENGURUSAN PELAJARAN'),
	(59, 'PENGURUSAN PROJEK'),
	(60, 'PENGURUSAN STRATEGIK'),
	(61, 'PENGURUSAN SUMBER MANUSIA'),
	(62, 'PENGURUSAN TEKNOLOGI'),
	(63, 'PENGURUSAN PENGGUNAAN TANAH'),
	(64, 'SAINS FIZIKAL'),
	(65, 'SAINS KANAK-KANAK'),
	(66, 'SAINS KEJURUTERAAN'),
	(67, 'SAINS KESIHATAN'),
	(68, 'SAINS KOMPUTER'),
	(69, 'SAINS KOMUNIKASI'),
	(70, 'SAINS MAKHLUK HIDUP'),
	(71, 'SAINS PENGURUSAN'),
	(72, 'SAINS PERSEKITARAN'),
	(73, 'SENI BINA'),
	(74, 'SENI HALUS'),
	(75, 'SENI VISUAL'),
	(76, 'SISTEM MAKLUMAT'),
	(77, 'SISTEM PENGURUSAN'),
	(78, 'SISTEM PENGURUSAN MAKLUMAT'),
	(79, 'SISTEM MAKLUMAT GEOGRAFIK'),
	(80, 'TEKNOLOGI BINAAN'),
	(81, 'TEKNOLOGI INDUSTRI'),
	(82, 'TEKNOLOGI MAKLUMAT'),
	(83, 'TEKNOLOGI PENGELUARAN'),
	(84, 'TEKNOLOGI PERUBATAN'),
	(85, 'TURISME'),
	(86, 'URUSAN ISLAM');

-- Dumping structure for table student_practical.lt_gender
CREATE TABLE IF NOT EXISTS `lt_gender` (
  `id_gender` int(2) NOT NULL AUTO_INCREMENT,
  `name_gender` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id_gender`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table student_practical.lt_gender: ~2 rows (approximately)
INSERT IGNORE INTO `lt_gender` (`id_gender`, `name_gender`) VALUES
	(1, 'LELAKI'),
	(2, 'PEREMPUAN');

-- Dumping structure for table student_practical.lt_ipta
CREATE TABLE IF NOT EXISTS `lt_ipta` (
  `id_ipta` int(3) NOT NULL AUTO_INCREMENT,
  `name_ipta` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`id_ipta`)
) ENGINE=InnoDB AUTO_INCREMENT=89 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table student_practical.lt_ipta: ~88 rows (approximately)
INSERT IGNORE INTO `lt_ipta` (`id_ipta`, `name_ipta`) VALUES
	(1, 'INSTITUT LATIHAN INDUSTRI MALAYSIA (ILIM)'),
	(2, 'INSTITUT LATIHAN PERINDUSTRIAN JEMPOL (ILPJ)'),
	(3, 'INSTITUT LATIHAN PERINDUSTRIAN KUALA LUMPUR (ILPKL)'),
	(4, 'INSTITUT LATIHAN PERINDUSTRIAN SULTAN AZLAN SHAH (ILPSAS)'),
	(5, 'INSTITUT KEMAHIRAN BELIA DAN SUMBER MANUSIA (IKBSM)'),
	(6, 'INSTITUT KEMAHIRAN MARA (IKM)'),
	(7, 'INSTITUT KEMAHIRAN POLIS DIRAJA MALAYSIA (IKPDRM)'),
	(8, 'INSTITUT PENDIDIKAN GURU KAMPUS KEDAH (IPGK KEDAH)'),
	(9, 'INSTITUT PENDIDIKAN GURU KAMPUS MALAYSIA (IPGK MALAYSIA)'),
	(10, 'INSTITUT PENDIDIKAN GURU KAMPUS PERAK (IPGK PERAK)'),
	(11, 'INSTITUT PENDIDIKAN GURU KAMPUS SARAWAK (IPGK SARAWAK)'),
	(12, 'INSTITUT PENGURUSAN PERNIAGAAN (IPP)'),
	(13, 'INSTITUT SULTAN IDRIS SHAH (ISIS)'),
	(14, 'INSTITUT TADBIR DAN PENGURUSAN (ITP)'),
	(15, 'INSTITUT TEKNOLOGI PETRONAS (ITP)'),
	(16, 'INSTITUT TEKNOLOGI SULTAN ISKANDAR (ITSI)'),
	(17, 'INSTITUT TEKNOLOGI UNIVERSITI MALAYSIA KELANTAN (UMK)'),
	(18, 'INSTITUT TEKNOLOGI UNIVERSITI MALAYSIA PAHANG (UMP)'),
	(19, 'INSTITUT TEKNOLOGI UNIVERSITI MALAYSIA TERENGGANU (UMT)'),
	(20, 'INSTITUT TEKNOLOGI UNIVERSITI SAINS MALAYSIA (USM)'),
	(21, 'INSTITUT TEKNOLOGI UNIVERSITI UTARA MALAYSIA (UUM)'),
	(22, 'KOLEJ KOMUNITI ALOR SETAR (KKAS)'),
	(23, 'KOLEJ KOMUNITI BANDAR PENAWAR (KKBP)'),
	(24, 'KOLEJ KOMUNITI BATU PAHAT (KKBP)'),
	(25, 'KOLEJ KOMUNITI BENTONG (KKB)'),
	(26, 'KOLEJ KOMUNITI BUKIT MERTAJAM (KKBM)'),
	(27, 'KOLEJ KOMUNITI CHUKAI (KKC)'),
	(28, 'KOLEJ KOMUNITI DUNGUN (KKD)'),
	(29, 'KOLEJ KOMUNITI GOMBAK (KKG)'),
	(30, 'KOLEJ KOMUNITI JEMPOL (KKJ)'),
	(31, 'KOLEJ KOMUNITI JOHOR BAHRU (KKJB)'),
	(32, 'KOLEJ KOMUNITI KELANTAN (KKK)'),
	(33, 'KOLEJ KOMUNITI KUALA LUMPUR (KKKL)'),
	(34, 'KOLEJ KOMUNITI KUALA TERENGGANU (KKKT)'),
	(35, 'KOLEJ KOMUNITI KUANTAN (KKQ)'),
	(36, 'KOLEJ KOMUNITI LANGKAWI (KKL)'),
	(37, 'KOLEJ KOMUNITI MELAKA (KKM)'),
	(38, 'KOLEJ KOMUNITI PENDANG (KKP)'),
	(39, 'KOLEJ KOMUNITI SABAH (KKS)'),
	(40, 'KOLEJ KOMUNITI SIBU (KKS)'),
	(41, 'KOLEJ KOMUNITI SIMPANG RENGGAM (KKSR)'),
	(42, 'KOLEJ KOMUNITI TANJUNG MALIM (KKT)'),
	(43, 'KOLEJ KOMUNITI TUMPAT (KKT)'),
	(44, 'KOLEJ KOMUNITI WANGSA MAJU (KKWM)'),
	(45, 'KOLEJ UNIVERSITI TUNKU ABDUL RAHMAN (TAR UC)'),
	(46, 'POLITEKNIK BATU PAHAT (PBP)'),
	(47, 'POLITEKNIK BANGI (PBG)'),
	(48, 'POLITEKNIK BELURAN (PBL)'),
	(49, 'POLITEKNIK DUNGUN (PDG)'),
	(50, 'POLITEKNIK JOHOR BAHRU (PJB)'),
	(51, 'POLITEKNIK KOTA BHARU (PKB)'),
	(52, 'POLITEKNIK KUALA LUMPUR (PKL)'),
	(53, 'POLITEKNIK KUANTAN (PKQ)'),
	(54, 'POLITEKNIK MELAKA (PM)'),
	(55, 'POLITEKNIK PENDIDIKAN PUNCAK ALAM (PPPA)'),
	(56, 'POLITEKNIK PORT DICKSON (PPD)'),
	(57, 'POLITEKNIK SABAH (PSB)'),
	(58, 'POLITEKNIK SEBERANG PERAI (PSP)'),
	(59, 'POLITEKNIK SEGAMAT (PSG)'),
	(60, 'POLITEKNIK SULTAN AZLAN SHAH (PSAS)'),
	(61, 'POLITEKNIK SULTAN HAJI AHMAD SHAH (PSHAS)'),
	(62, 'POLITEKNIK SULTAN IDRIS SHAH (PSIS)'),
	(63, 'POLITEKNIK TUANKU SYED SIRAJUDDIN (PTSS)'),
	(64, 'POLITEKNIK UNGKU OMAR (PUO)'),
	(65, 'POLITEKNIK WANGSA MAJU (PWM)'),
	(66, 'UNIVERSITI ALMA (UA)'),
	(67, 'UNIVERSITI DARUL IMAN MALAYSIA (UDM)'),
	(68, 'UNIVERSITI ISLAM ANTARABANGSA MALAYSIA (UIAM)'),
	(69, 'UNIVERSITI KEBANGSAAN MALAYSIA (UKM)'),
	(70, 'UNIVERSITI KUALA LUMPUR (UNIKL)'),
	(71, 'UNIVERSITI MALAYA (UM)'),
	(72, 'UNIVERSITI MALAYSIA KELANTAN (UMK)'),
	(73, 'UNIVERSITI MALAYSIA PAHANG (UMP)'),
	(74, 'UNIVERSITI MALAYSIA PERLIS (UniMap)'),
	(75, 'UNIVERSITI MALAYSIA SABAH (UMS)'),
	(76, 'UNIVERSITI MALAYSIA SARAWAK (UNIMAS)'),
	(77, 'UNIVERSITI MALAYSIA TERENGGANU (UMT)'),
	(78, 'UNIVERSITI PENDIDIKAN SULTAN IDRIS (UPSI)'),
	(79, 'UNIVERSITI PERTAHANAN NASIONAL MALAYSIA (UPNM)'),
	(80, 'UNIVERSITI PUTRA MALAYSIA (UPM)'),
	(81, 'UNIVERSITI SAINS ISLAM MALAYSIA (USIM)'),
	(82, 'UNIVERSITI SAINS MALAYSIA (USM)'),
	(83, 'UNIVERSITI SULTAN ZAINAL ABIDIN (USZA)'),
	(84, 'UNIVERSITI TEKNIKAL MALAYSIA MELAKA (UTeM)'),
	(85, 'UNIVERSITI TEKNOLOGI MARA (UiTM)'),
	(86, 'UNIVERSITI TEKNOLOGI MALAYSIA (UTM)'),
	(87, 'UNIVERSITI TUN HUSSEIN ONN MALAYSIA (UTHM)'),
	(88, 'UNIVERSITI UTARA MALAYSIA (UUM)');

-- Dumping structure for table student_practical.lt_level
CREATE TABLE IF NOT EXISTS `lt_level` (
  `id_level` int(2) NOT NULL AUTO_INCREMENT,
  `name_level` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id_level`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table student_practical.lt_level: ~2 rows (approximately)
INSERT IGNORE INTO `lt_level` (`id_level`, `name_level`) VALUES
	(1, 'ADMIN'),
	(2, 'STUDENT');

-- Dumping structure for table student_practical.tb_maklumat
CREATE TABLE IF NOT EXISTS `tb_maklumat` (
  `id_maklumat` int(3) NOT NULL AUTO_INCREMENT,
  `image_users` varchar(255) DEFAULT NULL,
  `resume_users` varchar(255) DEFAULT NULL,
  `id_users` int(3) DEFAULT NULL,
  `id_gender` int(2) DEFAULT NULL,
  `tarikh_lahir` varchar(15) DEFAULT NULL,
  `alamat` varchar(100) DEFAULT NULL,
  `no_telefon` varchar(15) DEFAULT NULL,
  `id_ipta` int(3) DEFAULT NULL,
  `no_matrik` varchar(25) DEFAULT NULL,
  `id_course` int(3) DEFAULT NULL,
  `tarikh_mula` varchar(15) DEFAULT NULL,
  `tarikh_tamat` varchar(15) DEFAULT NULL,
  PRIMARY KEY (`id_maklumat`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table student_practical.tb_maklumat: ~1 rows (approximately)
INSERT IGNORE INTO `tb_maklumat` (`id_maklumat`, `image_users`, `resume_users`, `id_users`, `id_gender`, `tarikh_lahir`, `alamat`, `no_telefon`, `id_ipta`, `no_matrik`, `id_course`, `tarikh_mula`, `tarikh_tamat`) VALUES
	(1, '1737528459-6885-images.png', '1737528459-9412-Klinik Dr Shuib Jan-2025.pdf', 6, 1, '23/02/1862', 'Menara MPSPK, Jalan Patani, Sungai Petani, 08000 Sungai Petani, Kedah', '0123456789', 63, '18DIP14F1025', 82, '01/01/2025', '31/01/2025');

-- Dumping structure for table student_practical.tb_users
CREATE TABLE IF NOT EXISTS `tb_users` (
  `id_users` int(3) NOT NULL AUTO_INCREMENT,
  `user_ic` varchar(50) DEFAULT NULL,
  `user_name` varchar(150) DEFAULT NULL,
  `user_email` varchar(50) DEFAULT NULL,
  `password` varchar(150) DEFAULT NULL,
  `user_level` int(2) DEFAULT NULL,
  PRIMARY KEY (`id_users`),
  UNIQUE KEY `user_ic` (`user_ic`),
  UNIQUE KEY `user_email` (`user_email`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table student_practical.tb_users: ~2 rows (approximately)
INSERT IGNORE INTO `tb_users` (`id_users`, `user_ic`, `user_name`, `user_email`, `password`, `user_level`) VALUES
	(1, '12345678910', 'Ikhwan', 'ikhwan@admin.com', '9c20781a692ef258abe6c9450a831d0f2142017e72cc86caf0c8e8ebcd5121356cd9f955153ac440df51d877946174fb24b038c48b3b8c116a31afd7ae14e0bd', 2),
	(2, '123456789000', 'MUHAMAD IKHWAN', 'admin@admin.com', 'c1728bbb71daa0991915545a52d0a4e393d70f6aed14294f291a645229f2d7496ea1967ecdf495a3ea714a5986485f21170adbe3098078d2113017d7acc1841f', 1);

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
